package com.example.muzik.myapplication.models

import com.example.muzik.myapplication.R

val muzicList = listOf(
    Music("Konsta", "Qorincha", R.raw.qorincha),
    Music("Konsta ft Sevara Nazarxon", "Asragin meni|REMIX", R.raw.asragin),
    Music("Konsta", "USA", R.raw.usa),
    Music("Konsta", "Tun", R.raw.tun),
    Music("Axror.A", "1,2,3", R.raw.axror),
    Music("Konsta ft Qarz", "Faktotum", R.raw.faktotum),
    Music("Lola ft Konsta", "Chidama", R.raw.chidama),
    Music("Konsta", "Sengacha", R.raw.sengacha),
    Music("Konsta ft Asl wayne ", "Chempion", R.raw.chempion),
    Music("Konsta", "Jonga tegdi", R.raw.jongategdi),
    Music("Konsta", "Hech kim yo'q", R.raw.hchkimyo),
    Music("Konsta ft Morf", "Bu shahar", R.raw.bushahar),
    Music("Konsta", "Qorincha", R.raw.qorincha),
    Music("Konsta", "To'y", R.raw.toy),
    Music("Konsta ft Lola", "Chidama remix", R.raw.chidamaremix),
    Music("Konsta", "Qor", R.raw.qor),
    Music("Konsta ft Shaka", "Kapalak", R.raw.shaka),
    Music("Konsta", "Santa", R.raw.santa),
    Music("Konsta ft Dilnoz", "U haqida", R.raw.uhaqida),
    Music("Konsta", "Bilmaydi", R.raw.bilmaydi),
    Music("Konsta", "Dada", R.raw.dada),
    Music("Axror.A", "Student", R.raw.student),
    Music("Konsta ft Shokir", "Ertasi yo bu", R.raw.ertasiyo),
    Music("Konsta", "Insonlar", R.raw.insonlar),
    Music("Konsta", "Maktab tugamaydi", R.raw.maktab),
    Music("Axror.A", "Uyda kutishadi", R.raw.uydakutishadi),
    Music("Konsta", "Jonga tegdi", R.raw.jongategdi),
    Music("Konsta", "Maska", R.raw.maska),
    Music("Konsta ft Temur Alixonov", "Meni do'stlarim chaqiradi boy deb", R.raw.menidostlarim),
    Music("Konsta", "Havotirlanmang", R.raw.havotirlanma),
    Music("Konsta", "Meni eslab", R.raw.menieslab),
    Music("Konsta", "Nafas", R.raw.nafas),
    Music("Temur Alixonov ft Konsta", "Odamlar nima deydi?", R.raw.odamlarnima),
    Music("Konsta", "Meni eslab", R.raw.menieslab),
    Music("M.Rizayeva ft Konsta", "O'ylamading", R.raw.oylamading),
    Music("Konsta", "Diplom", R.raw.diplom),
    Music("Konsta", "O'zbekistonlik", R.raw.ozbekistonlik),
    Music("Konsta", "Qizim", R.raw.qizim),
    Music("Konsta", "Baribir", R.raw.baribir),
    Music("Asl Wayne ft Konsta ft Morf", "Qo'l kiri", R.raw.qolikiripul)
)